Task_Keeper/Task_Keeper/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('tasks.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
]

Task_Keeper/tasks/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'tasks'

urlpatterns = [
path('login/',
         auth_views.LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', views.MainPage.as_view(), name='main'),
    path('add_group/', views.add_group, name='add_group'),
    path('edit_group/<int:id>/', views.edit_group, name='edit_group'),
    path('delete_group/<int:id>/', views.delete_group, name='delete_group'),
    path('board/', views.tasks, name='board'),
    path('details/<int:id>/', views.details, name='details'),
    path('add_task/<int:id>/', views.add_task, name='add_task'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('move/<int:id>/', views.move_to_next, name='move'),
]

Task_Keeper/tasks/models.py
from django.db import models
from django.contrib import auth


from django.contrib.auth import get_user_model

# Create your models here.
User2 = get_user_model()


class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return '{}'.format(self.username)


class Group(models.Model):
    user = models.ForeignKey(User2, related_name='columns', on_delete='CASCADE')
    group_name = models.CharField(max_length=150)
    group_order = models.IntegerField()


class Task(models.Model):
    user = models.ForeignKey(User2, related_name='tasks', on_delete='CASCADE')
    title = models.CharField(max_length=150)
    description = models.TextField(max_length=300)
    progress = models.CharField(max_length=150)
    priority = models.CharField(max_length=100, default='low')
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}: {}'.format(self.title, self.description)

Task_Keeper/tasks/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

Task_Keeper/Task_Keeper/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView


class ThanksPage(TemplateView):
    template_name = 'thanks.html'


class HomePage(TemplateView):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('tasks:main'))
        return super().get(request, *args, **kwargs)

Task_Keeper/tasks/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Task, Group
from django.contrib.auth import get_user_model
from . import forms

User = get_user_model()


class MainPage(LoginRequiredMixin, generic.TemplateView):
    template_name = 'tasks/main.html'


class SignUp(generic.CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


@login_required
def add_group(request):
    user = request.user
    if request.method == 'POST':
        group_name = request.POST['group_name']
        group_order = request.POST['group_order']
        group = Group(user=user, group_name=group_name, group_order=group_order)
        group.save()
        return HttpResponseRedirect('/tasks/board')
    else:
        return render(request, 'tasks/add_group.html')


@login_required
def edit_group(request, id):
    try:
        group = Group.objects.get(id=id)
        tasks = Task.objects.filter(progress=group.group_name)
        if request.method == 'POST':
            group.group_name = request.POST.get('group_name')
            group.save()
            for task in tasks:
                task.progress = group.group_name
                task.save()
            return HttpResponseRedirect('/tasks/board')
        else:
            return render(request, 'tasks/group_edit.html',
                          {'group': group})

    except Group.DoesNotExist:
        return HttpResponseRedirect('/tasks/board')


@login_required
def delete_group(request, id):
    try:
        group = Group.objects.get(id=id)
        group_tasks = Task.objects.filter(progress=group.group_name)
        group.delete()
        group_tasks.delete()
        return HttpResponseRedirect('/tasks/board')
    except Task.DoesNotExist:
        return HttpResponseNotFound('<h2>The group not found</h2>')


@login_required
def tasks(request):
    user = request.user
    tasks_user = Task.objects.filter(user=user)
    groups = Group.objects.filter(user=user).order_by("group_order")
    context = {
        'tasks': tasks_user,
        'groups': groups
    }
    return render(request, 'tasks/tasks.html', context)


@login_required
def details(request, id):
    task = Task.objects.get(id=id)
    context = {
        'task': task,
    }
    return render(request, 'tasks/details.html', context)


def get_group_context(user):
    groups = Group.objects.filter(user=user)
    return groups


@login_required
def add_task(request, id):
    user = request.user
    group = Group.objects.get(id=id)
    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']
        progress = group.group_name
        priority = request.POST['priority']
        task = Task(user=user,
                    title=title,
                    description=description,
                    progress=progress,
                    priority=priority)
        task.save()
        return HttpResponseRedirect('/tasks/board')
    else:
        current_group = Group.objects.get(id=id)
        return render(request, 'tasks/add_task.html', {'groups': get_group_context(user),
                                                       'id':group.id,
                                                       'current_group': current_group.group_name})


@login_required
def edit(request, id):
    try:
        task = Task.objects.get(id=id)
        if request.method == 'POST':
            task.title = request.POST.get('title')
            task.description = request.POST.get('description')
            task.progress = request.POST.get('progress')
            task.priority = request.POST.get('priority')
            task.save()
            return HttpResponseRedirect('/tasks/board')
        else:
            return render(request, 'tasks/edit.html',
                          {'task':task, 'groups':get_group_context})

    except Task.DoesNotExist:
        return HttpResponseRedirect('/tasks/board')


def index_plus(item, user):
    group_elem = Group.objects.filter(user=user)
    group_list = []
    for group in Group.objects.filter(user=user).order_by("group_order"):
        group_list.append(group.group_name)
    try:
        res = group_list[group_list.index(item) + 1]
        return res
    except IndexError:
        return item


@login_required
def move_to_next(request, id):
    user = request.user
    try:
        task = Task.objects.get(id=id)
        task.progress = index_plus(task.progress, user)
        task.save()
        return HttpResponseRedirect('/tasks/board')
    except Task.DoesNotExist:
        return HttpResponseRedirect('/tasks/board')


@login_required
def delete(request, id):
    try:
        task = Task.objects.get(id=id)
        task.delete()
        return HttpResponseRedirect('/tasks/board')
    except Task.DoesNotExist:
        return HttpResponseRedirect('/tasks/board')

Task_Keeper/tasks/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <h1>Log In</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-default" value="Login">
        </form>
    </div>
{% endblock %}

Task_Keeper/tasks/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <h1>Sign up</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-default" value="Sign Up">
        </form>
    </div>
{% endblock %}

Task_Keeper/tasks/templates/tasks/add_group.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <form class="form" action="{% url 'tasks:add_group' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Enter title of new group:</label><br>
                <input type="text" name="group_name" id="group_name">
                <label for="group_order">Point out the order number of your group:</label><br>
                <input type="number" name="group_order" id="group_order">
            </div>
            <br><br>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

Task_Keeper/tasks/templates/tasks/add_task.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <form class="form" action="{% url 'tasks:add_task' id %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Title</label><br>
                <input type="text" name="title" id="title">
            </div>
            <div class="form-group">
                <label for="description">Description</label><br>
                <textarea name="description" id="description"></textarea>
            </div>
            <label for="progress">Progress</label><br>
            <select name="progress">
                <option value="{{ current_group }}">{{ current_group }}</option>
            {% for group in groups %}
                <option value="{{ group.group_name }}">{{ group.group_name }}</option>
            {% endfor %}
            </select>
            <br>
            <label for="priority">Priority</label><br>
            <select name="priority">
                <option value="low">Low</option>
                <option value="middle">Middle</option>
                <option value="high">High</option>
            </select>
            <br><br>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

Task_Keeper/tasks/templates/tasks/details.html
{% extends "base.html" %}
{% block content %}
    <h2>The task details:</h2>
    <div class="jumbotron">
        <p><b>Title:</b> {{ task.title }}</p>
        <p><b>Description:</b> {{ task.description }}</p>
        <p><b>Priority:</b> {{ task.priority }}</p>
        <p><b>Stage of completing:</b> {{ task.progress }}</p>
        <p><b>Created on:</b> {{ task.created_at }}</p>
        <a href="{% url 'tasks:edit' task.id %}">Edit task</a>&nbsp | &nbsp
        <a href="{% url 'tasks:board' %}">Back to task list</a>&nbsp | &nbsp
        <a href="{% url 'tasks:delete' task.id %}">Delete</a>
    </div>
{% endblock %}

Task_Keeper/tasks/templates/tasks/edit.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <form action="{% url 'tasks:edit' task.id %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Title</label><br>
                <input type="text" name="title" id="title" value="{{ task.title }}">
            </div>
            <div class="form-group">
                <label for="description">Description</label><br>
                <textarea name="description" id="description">{{ task.description }}</textarea>
            </div>
            <label for="progress">Progress</label><br>
            <select name="progress" id="progress">
                <option value="{{ task.progress }}">{{ task.progress }}</option>
                {% for group in groups %}
                <option value="{{ group.group_name }}">{{ group.group_name }}</option>
            {% endfor %}
            </select><br>
            <label for="priority">Priority</label><br>
            <select name="priority" id="priority">
                <option value="{{ task.priority }}">{{ task.priority }}</option>
                <option value="low">Low</option>
                <option value="middle">Middle</option>
                <option value="high">High</option>
            </select>
            <br><br>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

Task_Keeper/tasks/templates/tasks/group_edit.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <form class="form" action="{% url 'tasks:edit_group' group.id %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Enter title of new group:</label><br>
                <input type="text" name="group_name" id="group_name" value="{{ group.group_name }}">
{#                <label for="group_order">Point out the order number of your group:</label><br>#}
{#                <input type="number" name="group_order" id="group_order">#}
            </div>
            <br><br>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

Task_Keeper/tasks/templates/tasks/main.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Task keeper app</h1>
    <h2><a href="{% url 'tasks:board' %}">Go to tasks list</a></h2>
{% endblock %}

Task_Keeper/tasks/templates/tasks/tasks.html
{% extends "base.html" %}
{% block content %}
    {% if groups %}
        {% for group in groups %}
        <div class="group">
            <h1>{{ group.group_name }}</h1>
            <a href="{% url 'tasks:add_task' group.id %}" class="ag">Add new task</a>&nbsp | &nbsp
            <a href="{% url 'tasks:edit_group' group.id %}" class="ag">Edit</a>&nbsp | &nbsp
            <a href="{% url 'tasks:delete_group' group.id %}" class="ag">Delete group</a>
            <hr>
            <br>
            {% for task in tasks %}
                {% if task.progress == group.group_name and task.title != ''%}
                    <div class="jumbotron">
                        <a href="{% url 'tasks:details' task.id %}">
                            <p><b>Title:</b> {{ task.title }}</p>
                        </a>
                        <p><b>Description:</b> {{ task.description }}</p>
                        <p><b>Priority:</b> {{ task.priority }}</p>
                        <p><b>Created on:</b> {{ task.created_at }}</p>
                        <a href="{% url 'tasks:edit' task.id %}">Change</a>&nbsp | &nbsp
                        <a href="{% url 'tasks:details' task.id %}">Details</a>&nbsp | &nbsp
                        <a href="{% url 'tasks:move' task.id %}">Move to next</a>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% endfor %}
    {% else %}
        <h1>No tasks or groups yet!</h1>
        <h2><a href="{% url 'tasks:add_group' %}">Create your first group of tasks</a></h2>
    {% endif %}

{% endblock %}

Task_Keeper/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Task keeper</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css'%}">



  </head>
  <body>

    <nav class="navbar mynav" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand mynav links" href="{% url 'home' %}"  class="">Task keeper</a>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'tasks:board' %}" class="links">Board</a></li>
            <li><a href="{% url 'tasks:add_group' %}" class="links">Create new group</a></li>
            <li><a href="{% url 'accounts:logout' %}" class="links">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'home' %}" class="links">Home</a></li>
            <li><a href="{% url 'accounts:login' %}" class="links">Log In</a></li>
            <li><a href="{% url 'accounts:signup' %}" class="links">Sign Up</a></li>
            {% endif %}
        </ul>

      </div>

    </nav>

    <div class="container mainest">

      {% block content %}

      {% endblock %}

    </div>

  </body>

</html>

Task_Keeper/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Task keeper app</h1>
    <h2>
        <a href="{% url 'accounts:signup' %}">Sign Up</a> or <a href="{% url 'accounts:login' %}">Log In</a>
        to set your task.
    </h2>
{% endblock %}

Task_Keeper/templates/thanks.html
{% extends "base.html" %}
{% block content %}

    <h1>Thanks for visiting, come back soon!</h1>
    <h2><a href="{% url 'home' %}">Main app page</a></h2>

{% endblock %}